Changed scope of db context factory to no longer be hard-coded to Scoped
koenbeuk/EntityFrameworkCore.Triggered pull request #136
Opened 2022-02-23 15:08 UTC by cdimitroulas

Closes #135

2022-02-24 08:19 UTC, cdimitroulas commented
@koenbeuk I see some tests are failing, in particular I noticed:
`EntityFrameworkCore.Triggered.Tests.Infrastructure.ServiceCollectionExtensionsTests.AddTriggeredDbContextFactory_WithCustomFactory_ReusesScopedServiceProvider`

Any advise on how to proceed?

2022-02-27 17:27 UTC, koenbeuk commented on src/EntityFrameworkCore.Triggered/Extensions/ServiceCollectionExtensions.cs
> +                    lifetime: lifetime
Instead of taking on the user requested lifetime, this needs to be `Transient` so that it always has the current ServiceProvider. Can you replace ServiceLifetime.Scoped with Transient?

2022-02-27 17:28 UTC, koenbeuk commented on src/EntityFrameworkCore.Triggered/Extensions/ServiceCollectionExtensions.cs
> +                    lifetime: lifetime
See above

2022-02-27 17:29 UTC, koenbeuk requested changes
I'm happy to accept this PR when we can change all hardcoded lifetimes from Scoped to Transient, see: https://github.com/koenbeuk/EntityFrameworkCore.Triggered/issues/135#issuecomment-1053622565

2022-02-28 10:47 UTC, cdimitroulas commented on src/EntityFrameworkCore.Triggered/Extensions/ServiceCollectionExtensions.cs
> +                    lifetime: lifetime
Done

2022-02-28 10:48 UTC, cdimitroulas commented
Updated as per your request @koenbeuk

2022-02-28 22:31 UTC, merged